---
- hosts: localhost
  connection: local

  tasks:

    - name: local config template
      template: src=local.sys.config.j2 dest=./local.sys.config
    - name: qa config template
      template: src=qa.sys.config.j2 dest=./qa.sys.config
    - name: pro config template
      template: src=pro.sys.config.j2 dest=./pro.sys.config

    - name: dog_start.sh template
      template: src=dog_start.sh.j2 dest=../dog_start.sh mode=744

    - name: dog_stop.sh template
      template: src=dog_stop.sh.j2 dest=../dog_stop.sh mode=744
